name: flutter_ws
description: A mobile Mediathek based on the MediathekView Web API.

dependencies:
  path_provider: '^0.5.0'
  sqflite: '^1.1.0'
  uuid: '^1.0.3'
  json_object_lite: '^2.0.0'
  device_info: '^0.4.0'
  url_launcher: '^5.0.0'
  socket_io: '^0.9.0+1'
  web_socket_channel: '^1.0.9'
  #dio: ^2.0.0
  # socket_io_client: '^0.9.1'
  # flutter_socket_io: '^0.4.6'
  logging: '^0.11.3+2'
  synchronized: '^1.5.3+2'
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/img/ic_distance.png
      - assets/img/tatort_background.jpg
      - assets/img/ard.png
      - assets/img/orf.png
      - assets/img/zdf.png
      - assets/img/wdr.png
      - assets/img/arte.png
      - assets/img/ndr.png
      - assets/img/3sat.png
      - assets/img/swr.png
      - assets/img/br.png
      - assets/img/dw.png
      - assets/img/hr.png
      - assets/img/kika.png
      - assets/img/mdr.png
      - assets/img/rbb.png
      - assets/img/srf.png
      - assets/img/background.jpg
      - assets/img/MediathekViewLoading.png
      - assets/default_live_stream_channels.txt

  fonts:
    - family: OldStandard
      fonts:
        - asset: assets/fonts/OldStandard-Regular.ttf
          weight: 600
        - asset: assets/fonts/OldStandard-Bold.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
