name: flutter_ws
description: A mobile Mediathek based on the MediathekView Web API.

dependencies:
  path_provider: '^0.4.0'
  sqflite: any
  uuid: '^0.5.3'
  json_object: '^1.0.19'
#  chewie: '^0.4.0'
  video_player: '^0.5.1'
  device_info: '^0.2.0'
  transparent_image: '^0.1.0'
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
      - assets/img/ic_distance.png
      - assets/img/tatort_background.jpg
      - assets/img/ard.png
      - assets/img/orf.png
      - assets/img/zdf.png
      - assets/img/wdr.png
      - assets/img/arte.png
      - assets/img/ndr.png
      - assets/img/3sat.png
      - assets/img/swr.png
      - assets/img/br.png
      - assets/img/dw.png
      - assets/img/hr.png
      - assets/img/kika.png
      - assets/img/mdr.png
      - assets/img/rbb.png
      - assets/img/srf.png
      - assets/img/background.jpg
      - assets/img/MediathekViewLoading.png
      - assets/default_live_stream_channels.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: OldStandard
      fonts:
        - asset: assets/fonts/OldStandard-Regular.ttf
          weight: 600
        - asset: assets/fonts/OldStandard-Bold.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
